# Generated by Django 3.2.3 on 2021-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='https://thumbs.dreamstime.com/z/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132484366.jpg'),
        ),
    ]
