# Generated by Django 3.2.4 on 2021-06-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_date_of_creating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_of_creating',
            field=models.DateTimeField(auto_created=True, default='2000-01-01 00:00'),
        ),
    ]
