# Generated by Django 3.2.3 on 2021-09-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210707_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='number_of_listings',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('NO', 'No category'), ('FS', 'Fashion'), ('TY', 'Toys'), ('EL', 'Electronics'), ('HM', 'Home'), ('MG', 'Magic things'), ('SP', 'Sport')], default='NO', max_length=2),
        ),
    ]
